### ISSUE TITLE
Create datalog query from JSON Schema or Typescript schema

### ISSUE THREAD

**Issue by gordonbrander** [commontoolsinc/synopsys#15]
- Derive queries automatically from Typescript or JSON Schema.
- Cells should contain json-typed data

**Comment by seefeldb** [comment]
A useful first step to unblock integration is just the ability to query open-ended JSON, i.e. what in typescript is:

type JSONValue =
  | string
  | number
  | boolean
  | null
  | JSONValue[]
  | { [key: string]: JSONValue };

**Comment by Gozala** [comment]
Closing this because I believe we have implemented most of this using builder DSLs in https://github.com/commontoolsinc/labs/tree/main/typescript/packages/lookslike-high-level/src/sugar
